### ISSUE TITLE
dataLabels.format bug when used multiline format

### ISSUE THREAD

**Issue by DedovR** [A----/highcharts-export-clientside#11]
I have a problem if I use "\<br/>" on <b>plotOptions.dataLabels.format</b>. Exporting charts have problem with labels. It's look like <a href="https://www.dropbox.com/s/myyvbjbwx4d533m/chart.jpeg?dl=0">this</a>:

**Comment by A----** [comment]
Could you work out a jsfiddle ( http://jsfiddle.net or http://codepen.io) of your isssue?

My guess is that it's due to bugs in canvas-tools. Maybe switching to a more recent version of canvg could solve this issue.

**Comment by DedovR** [comment]
I try recent version, it work good. But modules on <a href="http://code.highcharts.com/">code.highcharts.com</a> have problem when I try "Download jpeg/png Image".
http://jsfiddle.net/m2Lm6pgk/

**Comment by A----** [comment]
I updated your JsFiddle. First, it didn't use my plugin, so I plugged them in and it worked alright.
http://jsfiddle.net/m2Lm6pgk/1/

![chart](https://cloud.githubusercontent.com/assets/9195926/10246358/ca06caea-6910-11e5-9fe9-2d73b1805f1a.jpeg)
