### ISSUE TITLE
Excel export will not open in Excel 2010

### ISSUE THREAD

**Issue by zazzcode** [A----/highcharts-export-clientside#13]
Hi,
Was so excited to find your plug in for highcharts.  But when I download xls from your demo site and try to open in excel 2010 I get:

"The file you are tyring to open, 'monthly-average-temperature.xls', is in a different format than specified by the file extension..."

So the excel format seems to be incorrect.   

Would be great if the chart and data could export to excel.   Hope this can be fixed.

Thanks

**Comment by A----** [comment]
This comes from the `export-csv` dependency. Not much that I can do here. Not much that anybody can do about it I believe.

Here's the related issue: highslide-software/export-csv#41
