### ISSUE TITLE
Upload with an image (renderer)

### ISSUE THREAD

**Issue by GeoffreyOfficial** [A----/highcharts-export-clientside#14]
Hello,

I tried to export a chart with an image in it ( I use the fonction "renderer"). But this doesn't word. Like you can see here:
http://jsfiddle.net/sonf6Ln9/
Please can you help me ?

**Comment by A----** [comment]
Hi Geoffrey,

First, I can see the image in your jsfiddle. Next, what version are you using? Is it the latest one?
This issue seems linked to #1 and as been fixed in 1.1.0.

Regards.

**Comment by GeoffreyOfficial** [comment]
Hello, thank you for your answer ! =)

I change the version and this is better !!! but not good yet =)
I upadted the jsfiddle: http://jsfiddle.net/sonf6Ln9/1/

I can also see the image on the jsfiddle but when I try to export, I get "The operation is insecure" on jsfiddle. On my side, I get the chart but without image, I think that this is about the adress ... I mean when I add this "nice" sun "http://highcharts.com/demo/gfx/sun.png", this is ok, I get it. 
But when I want to add MY image "http://localhost/project/images/image_name.jpg", I have nothing in the export (only the chart).

Any idea ?

**Comment by A----** [comment]
Please read #1 in its entirety.

If you have this kind of error in the console:
```
Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```
Then you're using an image from a non-CORS-enabled source.
Check there for more information: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by GeoffreyOfficial** [comment]
ok thank you, I read, and I use the base64 and it works ! BUT like you said in the post, the scale doesn't work anymore ... so this is a problem, because the image is ugly without a scale :/

Is it possible to do something about it ?

**Comment by A----** [comment]
Sorry, it doesn't depend on my code, but on canvg I'd say. You can either set the scale option to 1 or scale the image manually.

**Comment by GeoffreyOfficial** [comment]
Ok thanks. But when I change the resolution manually, I get an issue.
The quality is good but the font-size is very very very small.

If I use 1000/690, I have 9 tick on Y and 11 ticks on X
IF I use 2000/1380, I have 19 ticks on Y and 21 ticks on X.

Then this is very difficult to read the image

I don't know what to do about it, I would like to have 2000*1380 with the same amount of tick that 1000*690

An idea ? (sorry to disturb you ... )

**Comment by A----** [comment]
I don't believe we're talking about the same thing, I'm talking about the `scale` options. Not `sourceWidth` / `sourceHeight`.

I don't really know why the scale is set to 2 by default (that's HighCharts default value, so it's mine too), but that's how it is. That shouldn't change the number of ticks, just the image size (that will be half its current size).

Reference's here: http://a----.github.io/highcharts-export-clientside/#reference

There's nothing more I can do in the current state of things, unfortunately.

**Comment by A----** [comment]
And yes, you can't have scaled images in the export. I'd say that `canvg` do not apply scaling to SVG assets when pasting on the canvas.

I hope you can work out a configuration that suits you.

**Comment by GeoffreyOfficial** [comment]
So, there is a misunderstanding. =)

Before I update the library(highcharts-export-clientside), this was perfect, I have
sourceWidth: 1000
sourceHeight: 690
scale: 5
And this was working perfectly.
BUT I added an image (renderer), then when I tried to export, I had nothing.

So I updated the library(highcharts-export-clientside), but I had to put scale: 1 or like you know there is a big issue.

So I tried this:
sourceWidth: 1000
sourceHeight: 690
scale: 1

And this work, but the image is ugly ^^

So I tried: 
sourceWidth: 2000
sourceHeight: 1380
scale: 1

Then, the quality is better but like you can see on the image, there is a lot of ticks ! so this is hard to read !


Your previous method (1.0.0) was working for the scale, but not the new one :)


![10m_20m dat-11](https://cloud.githubusercontent.com/assets/10940946/10193445/7464a1ea-6783-11e5-86f5-24d864442662.png)
![10m_20m dat-10](https://cloud.githubusercontent.com/assets/10940946/10193444/746200b6-6783-11e5-8288-8eb9aee332d0.png)

**Comment by A----** [comment]
The scale still works for everything but images.

You can still have a somewhat decent output by setting:
* `scale` to 1
* `sourceWidth` / `sourceHeight` to whatever you want
* and configure `chartOptions` for bigger fonts, less ticks, etc.

Or:
* `scale` /  `sourceWidth` / `sourceHeight` to whatever
* configure the `chartOptions` if feasible with a manually upscaled version of your image

**Comment by GeoffreyOfficial** [comment]
I am very glad that you try to help me ! =)

But please can you explain with examples. 
Here I have 3 jsfiddle, I only changed the libraries, nothing else. If I add your library, last version, scale is not working anymore. But if I add your library, first version, scale is working. So What I have to do ? you say that I can put scale to whatever ... Here I don't have image.

working (Default Highchart): http://jsfiddle.net/r5v2yfjo/
working (your library first version): http://jsfiddle.net/93yrb0qj/
not working (your library last version): http://jsfiddle.net/b5grLj7j/

I am really sorry to disturb you, but this is important for me :)

**Comment by A----** [comment]
Huh, okay… Big issue there. See #16 for that specific issue.
