### ISSUE TITLE
jsPDF – Cannot read config of undefined.

### ISSUE THREAD

**Issue by ScottSpittle** [A----/highcharts-export-clientside#15]
The jspdf seems to be giving this error. If i remoev jsfdp lib then all is fine.

**Comment by A----** [comment]
Real issue is there: MrRio/jsPDF#519 .
Downgrade jsPDF if this is a blocker for you.

**Comment by ScottSpittle** [comment]
Thanks.

**Comment by bjaraujo** [comment]
+1

**Comment by A----** [comment]
I'll state what I've already stated:

> Real issue is there: MrRio/jsPDF#519 .
> Downgrade jsPDF if this is a blocker for you.
