### ISSUE TITLE
Scale parameter doesn't work anymore

### ISSUE THREAD

**Issue by A----** [A----/highcharts-export-clientside#16]
@GeoffreyOfficial found out that when you `scale` attribute doesn't work anymore when used with `sourceWidth` / `sourceHeight`. See issue #14 .

**Comment by A----** [comment]
OK @GeoffreyOfficial, I pulled a hot-fix out of my hat. 
What was happening is that I changed the way `canvg` drew on the canvas from a shorthand to a longer version. Shorthand sets the option `ignoreDimensions` to `true` while the longer one assume `false`.

I'll do a proper release later. In the meanwhile, you can use the master branch.

JsFiddle: http://jsfiddle.net/b5grLj7j/1/

**Comment by A----** [comment]
Also, your example from the 1.0 could work. Raw github files are served as `text/plain` and those can't be used in a `<script />` tag.

More info there: http://geekdave.com/2013/06/19/linking-raw-github-files-from-jsfiddle/

**Comment by GeoffreyOfficial** [comment]
Can I call you, master or senpai ?
Anyway, you are a monster, thank you for this very very very v... fast update ! I have no problem, now, this is perfect, I have my image and the scale ! <3

**Comment by A----** [comment]
Sure :wink:

**Comment by A----** [comment]
Proper release is 1.1.3
