### ISSUE TITLE
Export PNG/JPG without download

### ISSUE THREAD

**Issue by moravcik** [A----/highcharts-export-clientside#17]
In my case I don't need to download the exported image but rather send it to server (in order to include it into PDF). Just the base64 representation would be fine. Is that possible with this lib?

**Comment by A----** [comment]
Not in its current state no, but with a bit of tweaking, yeah. This might not be the right approach though.
You might want to to rasterization on the server side.

You can get the SVG version of your chart using the official exporting plugin. Then it depends on what your backend is. Here's an example with FlyingSaucer + Batik: http://www.samuelrossille.com/posts/2013-08-13-render-html-with-svg-to-pdf-with-flying-saucer.html

**Comment by moravcik** [comment]
Thank you for your tip. We have problem to print some specific characters using FlyingSaucer and we don't want to use itextpdf due to strict licencing options.

Actually, we currently have an implementation based on official Highcharts' export server with usage of PhantomJS... but, we recently decided to keep server as simple as possible and not to introduce environment dependencies to server side and thus delegate as much work as possible to client. I have found few guides how to export chart to PNG/JPG via canvas (canvg). 

As I can see in the `renderPngJpeg` function you have the rasterized image available, but it is passed to download. If there is an option to make the download step optional and ability to provide callback/promise to get blob data it would work for me ;)

**Comment by A----** [comment]
If that's still what you want, then you probably don't need the whole library. Just put both the exporting plugin (to have access to `getSVG()`) and canvg/canvas-tools.

Then, something like that should do the trick:

```javascript
var svg = highChartsObject.getSVG(cChartOptions);

var canvas = document.createElement('canvas');

canvas.setAttribute('width', width);
canvas.setAttribute('height', height);

canvg(canvas, svg, {
  ignoreMouse: true,
  ignoreAnimation: true,
  ignoreDimensions: true,
  ignoreClear: true,
  offsetX: 0,
  offsetY: 0,
  scaleWidth: width,
  scaleHeight: height,
  renderCallback: function() {
    var dataURL = canvas.toDataURL("image/png");
  }
});
```

**Comment by moravcik** [comment]
Thank you, that worked like a charm
