### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by tallsam** [A----/highcharts-export-clientside#2]
That bower statement seems incomplete :)

```
Dependencies are not shipped, so you'll have to do the following:

bower install
```

**Comment by tallsam** [comment]
Also typo:

"This probably won't work on Internet Explorer **has** it uses HTML5 download feature and opens a data-uri as a fallback. "

**Comment by A----** [comment]
If you do a `bower install`, it'll fetch dependencies and you'll be able to run `example.html`. Which you be use mostly for contribution.

Install instructions are written there: http://a----.github.io/highcharts-export-clientside/#installation

But you're right, that should be clarified.

**Comment by A----** [comment]
Sorry to drop your pull request, I (finally) reworked the README page and I don't want to maintain both the README and the website, that's too error-prone.
