### ISSUE TITLE
Dynamic updates to chart.renderer.label won't get exported to images and PDF

### ISSUE THREAD

**Issue by ChartHeaven** [A----/highcharts-export-clientside#22]
If you dynamically update the label you created with chart.renderer.label, it won't get exported to images and PDF

Example:

Click on the "change label" button to dynamically update the label and then do the exporting.

http://jsfiddle.net/pscjzhe4/215/

**Comment by A----** [comment]
Now this is going to get tricky, but I've managed to make it work one time;
See the dependency chart here? http://a----.github.io/highcharts-export-clientside/ It still works when you resize the browser.
The magic's here: https://github.com/A----/highcharts-export-clientside/blob/gh-pages/js/dependency-tree.js#L53

**Comment by ChartHeaven** [comment]
Is this because you're not using the current chart instance (that includes the label change) for exporting?

Below is the code I'm trying to use and I don't understand why it's not using the current chart instance for exporting:

    onclick: function () {                                		
               this.exportChartLocal({                                        
                filename: Highcharts.exporting.USE_TITLE_FOR_FILENAME,
                type: Highcharts.exporting.MIME_TYPES.PDF
            });

http://jsfiddle.net/pscjzhe4/218/

**Comment by A----** [comment]
I was sure I answered you but heh.

The chart instance is the same, the renderers are different. It does not work even if you use an exporting server ( http://jsfiddle.net/pscjzhe4/219/ ). You'll have to hack into things.

Check how I did it.

**Comment by ChartHeaven** [comment]
Found another way to solve this puzzle!

Check this :)

http://jsfiddle.net/pscjzhe4/221/
