### ISSUE TITLE
dsahStyle not used in exported chart

### ISSUE THREAD

**Issue by georgetroughton** [A----/highcharts-export-clientside#33]
I have a chart where I use dashStyle: 'Dot' which works fine on the chart in the browser but when exported it does not use the dsahStyle and renders a solid line instead

**Comment by bouri-mounir** [comment]
I have the same issue

**Comment by bouri-mounir** [comment]
I found the solution in this discussion :)
https://github.com/A----/highcharts-export-clientside/issues/19

**Comment by georgetroughton** [comment]
Nice one thanks

**Comment by A----** [comment]
Thanks and sorry for not answering it sooner.
