### ISSUE TITLE
Highcharts.exporting.USE_TITLE_FOR_FILENAME broken with CSV and XLS

### ISSUE THREAD

**Issue by CWSites** [A----/highcharts-export-clientside#40]
I'm using this for `exporting.filename` and it works great for JPG, PNG and PDF however for CSV and XLS the filename is `function (options, chartOptions) {-    var title = this.title - this.title.textStr.replace(- -g, '-').toLowerCase() - 'chart';-    return title;-  }.csv`

**Comment by eleland** [comment]
Fwiw, and I realize this is probably a bit late, but I have a fix for this issue in this unmerged PR:
https://github.com/A----/highcharts-export-clientside/pull/26

**Comment by A----** [comment]
So am I apparently, merged.
