### ISSUE TITLE
How do I override to just allow PNG and JPEG?

### ISSUE THREAD

**Issue by mattjvincent** [A----/highcharts-export-clientside#43]
Is there a way to globally override all charts to just allow certain mime types?

**Comment by A----** [comment]
Yeah, that'd be a Highchart feature.

You can look at this, where I remove menu entries depending on browser support.
https://github.com/A----/highcharts-export-clientside/blob/master/highcharts-export-clientside.js#L131

You basically have to do the same and remove anything that is not JPEG/PNG.
