### ISSUE TITLE
Upgrade jsPDF dependency version in bower.json

### ISSUE THREAD

**Issue by tomascassidy** [A----/highcharts-export-clientside#6]
```bower update``` is telling me there is an update for ```jsPDF``` to version ```1.1.135```, but ```highcharts-export-clientside``` requires a previous version ```1.0.272```.  Is there any problem with upgrading the dependency version in ```bower.json```?

**Comment by A----** [comment]
Apparently not.
Did upgrade, and after a few tests, it seems fine.
