### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by aukevanleeuwen** [A----/highcharts-export-clientside#8]
When loading the required dependencies for exporting to JPG/PNG (i.e. canvas-tools) a javascript error appears:

`Uncaught TypeError: Cannot read property 'prototype' of undefined`

This is because `CanVGRenderer` is undefined [at this line](https://github.com/highslide-software/highcharts-release/blob/fdc36f76387be0484489bee074d8bd1f20f37a64/modules/canvas-tools.src.js#L2940): 

A quick search revealed these posts / issues:
* http://stackoverflow.com/questions/16149147/highcharts-canvas-tools-cannot-read-property-prototype-of-undefined
* https://github.com/highslide-software/highcharts.com/issues/2311

And the 'official response' is that the file shouldn't be included, but is loaded lazily on devices that don't support SVG (see http://api.highcharts.com/highcharts#global.canvasToolsURL).

**Comment by aukevanleeuwen** [comment]
As a workaround I included this script after loading the highcharts library and before including the canvas-tools.js:

```javascript
;(function () {
  'use strict';

  if (Highcharts != null && Highcharts.CanVGRenderer == null) {
    Highcharts.CanVGRenderer = {};
  }
})();
```

**Comment by A----** [comment]
Well, nothing much that I can do. I noticed that error but never got the time to dig what was causing it, so thanks for that.
Would you mind doing a pull request on their project? If so, can you link it here?

Another solution for this warning not to appear is to use canvg directly. But I had glitches with some versions of it (title appearing twice, from what I can remember) and since most sites also pack highcharts official modules…

**Comment by ScottSpittle** [comment]
I'm also getting this issue.

**Comment by A----** [comment]
Its more of an annoyance than an issue, as it works correctly with this warning. But as already stated, either create a pull-request on their repository or try to use `canvg` instead.

**Comment by ScottSpittle** [comment]
Ok, Thanks.

**Comment by A----** [comment]
You can try the latest release of `canvg` if this error is an issue for you.

**Comment by CWSites** [comment]
I was able to pull in `canvg` and include the files above `highcharts-export-clientside` and everything appears to be working fine; the error is gone.
