### ISSUE TITLE
Export array of charts?

### ISSUE THREAD

**Issue by Vaelyr** [A----/highcharts-export-clientside#9]
Would it somehow be possible here to export multiple charts as well?

**Comment by A----** [comment]
What do you mean, like multiple instances of highcharts stacked in the same image?

**Comment by Vaelyr** [comment]
Exactly

**Comment by A----** [comment]
As it is, no. It's possible to display multiple charts in the same instance of HighCharts and that would work, but not what you want to do.

With a bit of hack, you could put together something by exporting each chart in a different canvas, then stacking them up manually and downloading what's rendered.

**Comment by GeoffreyOfficial** [comment]
Hello,
Is it possible to modify this hack: http://jsfiddle.net/highcharts/gd7bB/ ?
And allow us to export different chart in the same image ?

**Comment by A----** [comment]
Yeah, I believe that this kind of hack can be used to combine two charts together.

**Comment by GeoffreyOfficial** [comment]
Thank you for your answer. The fact is that I tried but I can't get it .... Can you help me please ? :)

**Comment by A----** [comment]
Sorry @GeoffreyOfficial , it's kind of out of the scope of this plugin as it is now. But yeah, I'm planning a 2.0.0 when I'll get both time and motivation that'll be more flexible.
